### ISSUE TITLE
Skeletons

### ISSUE THREAD

**Issue by zanesterling** [Hypersonic/FistDance#13]
Implement a tree-based skeleton for animation, hitboxes, etc.

**Comment by Hypersonic** [comment]
Perhaps it would be useful to have named limbs/joints/whatever, so when animating you can say something along the lines of 
`left-arm goes from coords x1,y1,z1 to x2,y2,z2`
Obviously in a more formal way, but the idea is that you don't need to deal with numeric IDs or whatever for the limbs.

**Comment by zanesterling** [comment]
I have a couple suggestions to address that.
1. Allow labeling of limbs.
2. Have a few default labels, eg. the standard humanoid limbs.

**Comment by zanesterling** [comment]
Added by 653c9b492e09fd3f672035c4b40f33665f54af1a and previous commits.
