### ISSUE TITLE
Weird and wacky compiler error

### ISSUE THREAD

**Issue by zanesterling** [Hypersonic/FistDance#15]
![screen shot 2015-01-27 at 2 04 59 am](https://cloud.githubusercontent.com/assets/1170757/5914734/fd29b1c8-a5c8-11e4-8258-2dfa235d7e43.png)
Introduced in a9220e2b0b90af9c4d6eb9d04debbd81d3b836ef.

**Comment by Hypersonic** [comment]
Yeah I've been trying to figure this out. Probably going to revert the commit.

**Comment by zanesterling** [comment]
Push it to a branch, then revert it.

**Comment by Hypersonic** [comment]
Done, it's on vec2-fixes

**Comment by zanesterling** [comment]
Closed by 5584cafaf016edd4f4b9f63316c54f2a0278c12d
