### ISSUE TITLE
What is unload(Gamestate &) in core supposed to do?

### ISSUE THREAD

**Issue by zanesterling** [Hypersonic/FistDance#18]
It seems suspiciously like a looked-over duplicate of terminate.

**Comment by zanesterling** [comment]
Nevermind, after reading the code I've figured out the difference.

For future reference:
Unload gets run before unloading the dynamic lib.
Terminate gets run before the program exits.

**Comment by Hypersonic** [comment]
Perhaps this could be more clearly commented, but you are correct, that is the behavior.
