### ISSUE TITLE
Nodes should take a name that can be used to refer to them in animation

### ISSUE THREAD

**Issue by Hypersonic** [Hypersonic/FistDance#22]

**Comment by zanesterling** [comment]
Node-naming added in
19266b4ebc6d0d8334496e98a0cd5cbb025506b2

**Comment by Shriken** [comment]
1afd786bb5409520060ca673cafba55f76afea35

**Comment by zanesterling** [comment]
Node-naming adjusted to desired scheme in 1afd786bb5409520060ca673cafba55f76afea35
